### ISSUE TITLE
Add Italian translation

### ISSUE THREAD

**Issue by edmael** [devmount/you-can-quit#14]
Hi,
I'd like to add the italian translation for this project.
I've seen the de.json translation in /src/locales, can I just add the it.json file there or is there more to do?

**Comment by dennybiasiolli** [comment]
@edmael I think you have to add a line also in [src/main.js#L101](https://github.com/devmount/you-can-quit/blob/master/src/main.js#L101) file.
Also, check if there are components for choosing between locales.

**Comment by devmount** [comment]
Awesome, thank you @edmael for your contribution and @dennybiasiolli for the quick reply. I will soon review the PR and merge it.
