### ISSUE TITLE
There's no way to switch language

### ISSUE THREAD

**Issue by edmael** [devmount/you-can-quit#15]
Right now the app is shown in the same language as your browser (or in english if that language is not available).
There should be a language switcher (maybe in the footer?) to force a display language for those who wants to change it.

**Comment by devmount** [comment]
Thank you for this idea, I like it! It would be useful for those, whose browser language doesn't exist but who would prefer another language than English.

**Comment by devmount** [comment]
I implemented it:

![image](https://user-images.githubusercontent.com/5441654/94920470-ac86b380-04b6-11eb-9b97-51b8badebfa9.png)

I will soon publish the next release with it. Thanks again for this idea!
